ORG 0000H
MOV P0,#0XFF; SETTING ALL THE BITS OF PORT 0 
READ: MOV A,P0; READING THE CONTENT OF PORT 0
CJNE A,#0XFC,LED_OFF; CHECKING THE CONTENT OF ACCUMULATOR WITH THE IMMEDIATE DATA
CLR P1.0; IF THE ABOVE CONDITION IS FALSE LED GLOWS
SJMP READ
LED_OFF: SETB P1.0; SETTING THE LED 
SJMP READ
END
