ORG 0000H
MOV P0,#0XFF; SETTING THE SINK BITS 
READ:MOV A, P0; GETTING THE VALUE TO ACUUMULATOR
CJNE A,#0XFF,LEAD_ON; CHECKING THE CONDITON
SETB P1.0; LED OFF
SJMP READ
LEAD_ON:CLR P1.0; LED GLOWS
SJMP READ
END
